import '../../../node_modules/reset-css/sass/_reset.scss';
import '../../variables.scss';
import '../../components/page/page.js';
import '../../components/ui_kit/ui_kit.js';
import '../../components/input/input.js';
import '../../components/checkbox/checkbox.js';
import '../../components/radio/radio.js';
import '../../components/toggle/toggle.js';
import '../../components/like/like.js';
import './form_elements.scss';
// import './form_elements.pug';